// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Data.Entities
{
    public partial class AspNetRoleClaim 
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [StringLength(450)]
        public string RoleId { get; set; }

        [StringLength(128)]
        public string ClaimType { get; set; }

        [StringLength(128)]
        public string ClaimValue { get; set; }

        //[ForeignKey(nameof(RoleId))]
        //[InverseProperty(nameof(AspNetRole.AspNetRoleClaims))]
        //public virtual AspNetRole Role { get; set; }
    }
}